{{ config(materialized='table') }}

with source_data as (

    select distinct
        TRY_CAST(DATE AS DATE) AS DATE,
        TRY_CAST(DATE_TYPE AS VARCHAR(255)) AS DATE_TYPE,
        TRY_CAST(MMWR_WEEK AS INT) AS MMWR_WEEK,
        TRY_CAST(LOCATION AS VARCHAR(2)) AS LOCATION,
        TRY_CAST(ADMINISTERED_DAILY AS FLOAT) AS ADMINISTERED_DAILY,
        TRY_CAST(ADMINISTERED_CUMULATIVE AS FLOAT) AS ADMINISTERED_CUMULATIVE,
        TRY_CAST(ADMIN_DOSE_1_DAILY AS FLOAT) AS ADMIN_DOSE_1_DAILY,
        TRY_CAST(ADMIN_DOSE_1_CUMULATIVE AS FLOAT) AS ADMIN_DOSE_1_CUMULATIVE,
        TRY_CAST(ADMINISTERED_DOSE1_POP_PCT AS FLOAT) AS ADMINISTERED_DOSE1_POP_PCT,
        TRY_CAST(SERIES_COMPLETE_DAILY AS FLOAT) AS SERIES_COMPLETE_DAILY,
        TRY_CAST(SERIES_COMPLETE_CUMULATIVE AS FLOAT) AS SERIES_COMPLETE_CUMULATIVE,
        TRY_CAST(SERIES_COMPLETE_POP_PCT AS FLOAT) AS SERIES_COMPLETE_POP_PCT,
        TRY_CAST(BOOSTER_DAILY AS FLOAT) AS BOOSTER_DAILY,
        TRY_CAST(BOOSTER_CUMULATIVE AS FLOAT) AS BOOSTER_CUMULATIVE,
        TRY_CAST(ADDITIONAL_DOSES_VAX_PCT AS FLOAT) AS ADDITIONAL_DOSES_VAX_PCT,
        TRY_CAST(SECOND_BOOSTER_50PLUS_DAILY AS FLOAT) AS SECOND_BOOSTER_50PLUS_DAILY,
        TRY_CAST(SECOND_BOOSTER_50PLUS_CUMULATIVE AS FLOAT) AS SECOND_BOOSTER_50PLUS_CUMULATIVE,
        TRY_CAST(SECOND_BOOSTER_50PLUS_VAX_PCT AS FLOAT) AS SECOND_BOOSTER_50PLUS_VAX_PCT,
        TRY_CAST(BIVALENT_BOOSTER_DAILY AS FLOAT) AS BIVALENT_BOOSTER_DAILY,
        TRY_CAST(BIVALENT_BOOSTER_CUMULATIVE AS FLOAT) AS BIVALENT_BOOSTER_CUMULATIVE,
        TRY_CAST(BIVALENT_BOOSTER_POP_PCT AS FLOAT) AS BIVALENT_BOOSTER_POP_PCT
    from {{ source('covid_raw', 'VACCINATION_TRENDS') }}
    where DATE_TYPE = 'Admin'
)

select 
	DATE as vaccination_date,
    DATE_TYPE as date_type,
    MMWR_WEEK as mmwr_week,
    LOCATION as state_abbrev,
    ADMINISTERED_DAILY as administered_daily,
    ADMINISTERED_CUMULATIVE as administered_cumulative,
    ADMIN_DOSE_1_DAILY as admin_dose_1_daily,
    ADMIN_DOSE_1_CUMULATIVE as admin_dose_1_cumulative,
    ADMINISTERED_DOSE1_POP_PCT as administered_dose1_pop_pct,
    SERIES_COMPLETE_DAILY as series_complete_daily,
    SERIES_COMPLETE_CUMULATIVE as series_complete_cumulative,
    SERIES_COMPLETE_POP_PCT as series_complete_pop_pct,
    BOOSTER_DAILY as booster_daily,
    BOOSTER_CUMULATIVE as booster_cumulative,
    ADDITIONAL_DOSES_VAX_PCT as additional_doses_vax_pct,
    SECOND_BOOSTER_50PLUS_DAILY as second_booster_50plus_daily,
    SECOND_BOOSTER_50PLUS_CUMULATIVE as second_booster_50plus_cumulative,
    SECOND_BOOSTER_50PLUS_VAX_PCT as second_booster_50plus_vax_pct,
    BIVALENT_BOOSTER_DAILY as bivalent_booster_daily,
    BIVALENT_BOOSTER_CUMULATIVE as bivalent_booster_cumulative,
    BIVALENT_BOOSTER_POP_PCT as bivalent_booster_pop_pct
from source_data