{{ config(materialized='table') }}

with source_data as (

    select distinct
        WEEKENDINGDATE,
        JURISDICTION,
        NUMINPTBEDS,
        NUMINPTBEDSADULT,
        NUMINPTBEDSPED,
        NUMINPTBEDSOCC,
        NUMINPTBEDSOCCADULT,
        NUMINPTBEDSOCCPED,
        NUMICUBEDS,
        NUMICUBEDSADULT,
        NUMICUBEDSPED,
        NUMICUBEDSOCC,
        NUMICUBEDSOCCADULT,
        NUMICUBEDSOCCPED,
        NUMCONFC19HOSPPATSADULT,
        NUMCONFC19HOSPPATSPED,
        TOTALCONFC19HOSPPATS,
        NUMCONFC19ICUPATSADULT,
        NUMCONFC19ICUPATSPED,
        TOTALCONFC19ICUPATS,
        NUMCONFC19NEWADMPED0TO4,
        NUMCONFC19NEWADMPED5TO17,
        TOTALCONFC19NEWADMPED,
        NUMCONFC19NEWADMADULT18TO49,
        TOTALCONFC19NEWADMADULT,
        NUMCONFC19NEWADMUNK,
        TOTALCONFC19NEWADM,
        TOTALCONFC19HOSPPATSHOSPREP,
        TOTALCONFC19NEWADMHOSPREP,
        NUMCONFC19NEWADMPED0TO4PER100K,
        NUMCONFC19NEWADMPED5TO17PER100K,
        TOTALCONFC19NEWADMPEDPER100K,
        NUMCONFC19NEWADMADULT18TO49PER100K,
        TOTALCONFC19NEWADMADULTPER100K,
        TOTALCONFC19NEWADMPER100K,
        RESPSEASON,
        TOTALCONFC19NEWADMCUMULATIVESEASONALSUM,
        TOTALCONFNEWADMCUMULATIVESEASONALSUM
    from {{ source('covid_raw', 'HOSPITAL_METRICS') }}
)

select 
	WEEKENDINGDATE as week_ending_date,
    JURISDICTION as state_abbrev,
    NUMINPTBEDS as num_inpatient_beds,
    NUMINPTBEDSADULT as num_inpatient_beds_adult,
    NUMINPTBEDSPED as num_inpatient_beds_ped,
    NUMINPTBEDSOCC as num_inpatient_beds_occ,
    NUMINPTBEDSOCCADULT as num_inpatient_beds_occ_adult,
    NUMINPTBEDSOCCPED as num_inpatient_beds_occ_ped,
    NUMICUBEDS as num_icu_beds,
    NUMICUBEDSADULT as num_icu_beds_adult,
    NUMICUBEDSPED as num_icu_beds_ped,
    NUMICUBEDSOCC as num_icu_beds_occ,
    NUMICUBEDSOCCADULT as num_icu_beds_occ_adult,
    NUMICUBEDSOCCPED as num_icu_beds_occ_ped,
    NUMCONFC19HOSPPATSADULT as covid_hospitalized_adults,
    NUMCONFC19HOSPPATSPED as covid_hospitalized_ped,
    TOTALCONFC19HOSPPATS as total_covid_hospitalized,
    NUMCONFC19ICUPATSADULT as covid_icu_patients_adult,
    NUMCONFC19ICUPATSPED as covid_icu_patients_ped,
    TOTALCONFC19ICUPATS as total_covid_icu_patients,
    NUMCONFC19NEWADMPED0TO4 as covid_new_admissions_ped_0_to_4,
    NUMCONFC19NEWADMPED5TO17 as covid_new_admissions_ped_5_to_17,
    TOTALCONFC19NEWADMPED as total_covid_new_admissions_ped,
    NUMCONFC19NEWADMADULT18TO49 as covid_new_admissions_adult_18_to_49,
    TOTALCONFC19NEWADMADULT as total_covid_new_admissions_adult,
    NUMCONFC19NEWADMUNK as covid_new_admissions_unk,
    TOTALCONFC19NEWADM as total_covid_new_admissions,
    TOTALCONFC19HOSPPATSHOSPREP as total_covid_hospitalized_hosprep,
    TOTALCONFC19NEWADMHOSPREP as total_covid_new_admissions_hosprep,
    NUMCONFC19NEWADMPED0TO4PER100K as covid_new_admissions_ped_0_to_4_per_100k,
    NUMCONFC19NEWADMPED5TO17PER100K as covid_new_admissions_ped_5_to_17_per_100k,
    TOTALCONFC19NEWADMPEDPER100K as total_covid_new_admissions_ped_per_100k,
    NUMCONFC19NEWADMADULT18TO49PER100K as covid_new_admissions_adult_18_to_49_per_100k,
    TOTALCONFC19NEWADMADULTPER100K as total_covid_new_admissions_adult_per_100k,
    TOTALCONFC19NEWADMPER100K as total_covid_new_admissions_per_100k,
    RESPSEASON as resp_season,
    TOTALCONFC19NEWADMCUMULATIVESEASONALSUM as total_covid_new_admissions_cumulative_seasonal_sum,
    TOTALCONFNEWADMCUMULATIVESEASONALSUM as total_respiratory_new_admissions_cumulative_seasonal_sum
from source_data
